// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewStatus } from "./ReviewStatus";

export type CreateReviewRequest = {
  criterionId: string;
  status: ReviewStatus;
  comment: string;
  evidenceDocumentIds: Array<string>;
};
