// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentStatus } from "./DocumentStatus";

export type DocumentDetail = {
  id: string;
  title: string;
  fileName: string;
  status: DocumentStatus;
  content: string;
  /**
   * ISO 8601 UTC 문자열
   */
  createdAt: string;
};
