// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentListItem } from "./DocumentListItem";

export type ListDocumentsResponse = { documents: Array<DocumentListItem> };
