// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewStatus } from "./ReviewStatus";

export type Review = {
  id: string;
  criterionId: string;
  status: ReviewStatus;
  comment: string;
  evidenceDocumentIds: Array<string>;
  /**
   * ISO 8601 UTC 문자열
   */
  createdAt: string;
  /**
   * ISO 8601 UTC 문자열
   */
  updatedAt: string;
};
